name: 'algm-drutiny-build'
description: 'This action will create a docker container and output the druity phar'
inputs:
  tag-ref:
    description: 'The tag version for the phar build'
    required: true
    default: 'latest'
  composer-packages:
    description: 'Composer packages to include'
outputs:
  phar:
    description: 'The phar file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag-ref }}
    - ${{ inputs.composer-packages }}
