name: 'algm-drutiny-build'
description: 'This action will create a docker container and output the druity phar'
inputs:
  tag-ref:
    description: 'The tag version for the phar build'
    required: true
    default: 'latest'
  composer-packages:
    description: 'Composer packages to include'
  composer-repos:
    description: 'Composer drutiny repo to include'
    default: 'amazeelabs/algm_drutiny_plugin vcs https://github.com/AmazeeLabs/algm_drutiny.git'
outputs:
  phar:
    description: 'The phar file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag-ref }}
    - ${{ inputs.composer-packages }}
    - ${{ inputs.composer-repos }}
